### ISSUE TITLE
不移之火和VR开发网测试失败

### ISSUE THREAD

**Issue by DTEX123** [Miao-Mico/sspanel.soulsign#1]
显示签到成功实际上并没有
https://www.byzhihuo.com/plugin.php?id=dsu_paulsign:sign
https://www.52vr.com/plugin.php?id=dsu_paulsign:sign

**Comment by miiwu** [comment]
> 显示签到成功实际上并没有
> https://www.byzhihuo.com/plugin.php?id=dsu_paulsign:sign
> https://www.52vr.com/plugin.php?id=dsu_paulsign:sign

@DTEX123 谢反馈呀，发现是判断是否已经签到关键字的问题。
已尝试解决，请更新 `discuz`。
