### ISSUE TITLE
迅维网签到脚本特异点

### ISSUE THREAD

**Issue by yi-Xu-0100** [Miao-Mico/sspanel.soulsign#2]
特异点：该论坛注册用户需要付费开通签到和回帖的权限。
如果没有开通相关权限，使用通用模板，签到返回数据会包含信息：您所在用户组不允许使用

其他返回符合通用模板特性，暂无特别发现。
当然不同论坛对于积分用途的说明和名称设定也是不同的，迅维网的积分称为下载分。

**Comment by miiwu** [comment]
尝试过使用 [`discuz.k`](https://soulsign.inu1255.cn/scripts/229) 在 `配置参数` 里的 `域名` 填上 `www.chinafix.com` 跑一下嘛，能行嘛？
我现在还没账号，没法测试。

![image](https://user-images.githubusercontent.com/42897857/90368902-64920580-e09d-11ea-8f32-bf786a4e155a.png)

**Comment by yi-Xu-0100** [comment]
会直接显示签到成功，应该是不对的，我没有付费，没有权限签到才对

**Comment by miiwu** [comment]
> 会直接显示签到成功，应该是不对的，我没有付费，没有权限签到才对

ok，那看来得解析一下返回的数据了，你可以去看看 [`discuz.dc`](https://soulsign.inu1255.cn/script/Miao-Mico/discuz.dc.js)。
里面包含解析的部分，`.hook.post_sign_in`。
不过还得是返回数据格式差不多才行，你可以输出一下数据，贴上来我看看吗，在 `f12` 里的网络那边.

![image](https://user-images.githubusercontent.com/42897857/90369484-7031fc00-e09e-11ea-9807-36d888fabb75.png)

可以有这种效果：

![image](https://user-images.githubusercontent.com/42897857/90369777-e8002680-e09e-11ea-9546-88533128e868.png)

![image](https://user-images.githubusercontent.com/42897857/90369932-20076980-e09f-11ea-896f-015c1821e4f0.png)

**Comment by yi-Xu-0100** [comment]
返回数据如下：

``` html
<?xml version="1.0" encoding="gbk"?>
<root><![CDATA[您所在用户组不允许使用]]></root>
```

**Comment by miiwu** [comment]
> 返回数据如下：
> 
> ```
> <?xml version="1.0" encoding="gbk"?>
> <root><![CDATA[您所在用户组不允许使用]]></root>
> ```

好，我先看看。

我也希望你可以看看我写的[应用脚本](https://github.com/miiwu/sspanel.soulsign/tree/master/application)，也可以帮我改改，提提意见啥的。😆

**Comment by yi-Xu-0100** [comment]
感觉如果多个站点写在一起的话，这个样式可能不太适合了，点击查看日志的功能可能会对你这个显示会好点。

就是一直提示未实现的功能。这样，可以只在那个小栏中显示签到成功多少，失败多少，详细信息的话，点击查看。

当然这个功能还有待实现。

**Comment by miiwu** [comment]
> 感觉如果多个站点写在一起的话，这个样式可能不太适合了，点击查看日志的功能可能会对你这个显示会好点。
> 
> 就是一直提示未实现的功能。这样，可以只在那个小栏中显示签到成功多少，失败多少，详细信息的话，点击查看。
> 
> 当然这个功能还有待实现。

这个的话，你可以把 `.sign_in(true)` 里面的 `true` 去掉，这样就只显示失败的了，如果成功就不显示出来。
我原来是不全输出的，但是我看有些脚本把详细信息列出来了，就默认全输出了。
到时候把它列到 `配置参数` 里，就可单独配置了。

上面这个方法只是折中，当然你说的这个实现了的话，会更好呀。

![image](https://user-images.githubusercontent.com/42897857/90370729-72955580-e0a0-11ea-928d-1ece167d6c6d.png)
![image](https://user-images.githubusercontent.com/42897857/90370836-a07a9a00-e0a0-11ea-8455-3c2beab42852.png)

**Comment by yi-Xu-0100** [comment]
主要，一般都是详细和概况都想兼顾，所以日志功能才会有所需求。
如果单站点单脚本的话，可能通知信息比较少，看起来还不算拥挤。
你的这种，一方面可能我还是想保留能看详细信息的方式，又不想不注意的时候，还显示那么多。
所以日志功能可能更满足我的需求。
如果默认一个设置的话，我想看今天的详细信息是看不到的。调换设置，当天要么是简略消息，换成详细信息设置，也只能显示全部重复签到了。

**Comment by miiwu** [comment]
> 主要，一般都是详细和概况都想兼顾，所以日志功能才会有所需求。
> 如果单站点单脚本的话，可能通知信息比较少，看起来还不算拥挤。
> 你的这种，一方面可能我还是想保留能看详细信息的方式，又不想不注意的时候，还显示那么多。
> 所以日志功能可能更满足我的需求。
> 如果默认一个设置的话，我想看今天的详细信息是看不到的。调换设置，当天要么是简略消息，换成详细信息设置，也只能显示全部重复签到了。

对，大佬说的是，不过，我暂时只能想到这么搞，折中一下，哈哈哈。

还有，对于签到完提取提示的部分，得等段时间。
可能明早会更新，我得确定其他网站的签到结束是不是也是这个型式才行。

不过，过会我可以单独把这个搞一下，你可以在你自己的脚本上试试，到时候确定格式，我会更新脚本。
也就差这个没提取了，其他两个 `discuz` 系列都有。

**Comment by yi-Xu-0100** [comment]
单脚本的话，考虑的可能少点，只是对单站点匹配就好，我的迅维网签到基本就改了域名，添加了一条判断特异点的地方就好。其他的只是结构上的优化，后期类似的论坛可能基本以这个为模板复制粘贴，全文替换域名就好了。

赞叹你对统筹脚本，做统一方式签到的思路，如果后期又更好的信息输出方式，我想这个是好的方法。

**Comment by miiwu** [comment]
你试试行了嘛。

`
/* 正则匹配消息 */
return { code: 0, data: data_psi.match(/\[[^\[]+\[(.*[^\]]+)\]/)[1] };
`

提取主要是用到了 `正则表达式`。

![image](https://user-images.githubusercontent.com/42897857/90374118-90b18480-e0a5-11ea-9d16-2dd7b1894449.png)

**Comment by miiwu** [comment]
> 单脚本的话，考虑的可能少点，只是对单站点匹配就好，我的迅维网签到基本就改了域名，添加了一条判断特异点的地方就好。其他的只是结构上的优化，后期类似的论坛可能基本以这个为模板复制粘贴，全文替换域名就好了。
> 
> 赞叹你对统筹脚本，做统一方式签到的思路，如果后期又更好的信息输出方式，我想这个是好的方法。

我在搞在日志里可以有超链接，换行符，那样就可以克服多网站登录和排版问题了。
哈哈哈，一直有毛病。还没通过 `pull request`。

**Comment by yi-Xu-0100** [comment]
我不知道你更新的是哪个脚本，我使用了市场中的 `discuz.k`，`discuz.dc`, `discuz`，第一个好像没有更新，还是显示签到成功。
第2，3个直接显示未登录，我是登陆的。

**Comment by miiwu** [comment]
> 我不知道你更新的是哪个脚本，我使用了市场中的 `discuz.k`，`discuz.dc`, `discuz`，第一个好像没有更新，还是显示签到成功。

我没更新呢，你先替换本地脚本，试试看，如果更新得兼容其他网站。
我可能得用点马甲去实验，或者等到晚上，都还没签到的时候，看返回信息。

> 第 2，3 个直接显示未登录，我是登陆的。

什么情况，都是什么网址，是我写的兼容的嘛？

其他的两个是为了支持别的类型的 `discuz` 签到插件，分开的。
如果还是刚刚那个网站，它就是 `k` 类型的，不能使用其他两个。
可以通过签到地址来判断，[看这里](https://github.com/miiwu/sspanel.soulsign/blob/master/application/readme.md)。

**Comment by yi-Xu-0100** [comment]
我只设置了参数域名那一项，使用了  `www.chinafix.com` 作为参数。没有看脚本主页的信息，后两个应该本不支持迅维网。

使用 `discuz.k` 现在能够返回签到失败了，但是无法给出失败原因，签到返回的信息没有给出。

当前返回的信息还是比较特异的，感觉不常见。可以直接对当前情况进行特殊判断。

**Comment by miiwu** [comment]
> 我只设置了参数域名那一项，使用了 `www.chinafix.com` 作为参数。没有看脚本主页的信息，后两个应该本不支持迅维网。
> 
> 使用 `discuz.k` 现在能够返回签到失败了，但是无法给出失败原因，签到返回的信息没有给出。
> 
> 当前返回的信息还是比较特异的，感觉不常见。可以直接对当前情况进行特殊判断。

我猜死在了，获取 `JD_sign` 字段那里可能，把第一个请求的网址的返回值搜索一下，应该是 `plugin.php?id=k_misign:sign` 这个，字应该挺多，看看有没有 `JD_sign` 这个字段。

要么就是我刚刚贴的正则出错了。

我看着改改，这个确实存在毛病，不是指定地址而是从网页获取的话，跟其他两个都不太一样。

**Comment by yi-Xu-0100** [comment]
感觉是正则问题，因为我的脚本也是查的 `JD_sign` 这个字段。你的正则是匹配返回结果码？

**Comment by miiwu** [comment]
> 感觉是正则问题，因为我的脚本也是查的 `JD_sign` 这个字段。你的正则是匹配返回结果码？

对，匹配 `.post()` 的返回结果。

**Comment by yi-Xu-0100** [comment]
``` js
 /* 正则匹配消息 */
return { code: 0, data: data_psi.data.match(/\[[^\[]+\[(.*[^\]]+)\]/)[1] };
```

使用上面的就行了，能够返回出信息了，然后就是测试真实签到的实验，需要那个提出该脚本的人来测试了，你可以在那个 issue 下问问他。

**Comment by miiwu** [comment]
> 使用上面的就行了，能够返回出信息了，然后就是测试真实签到的实验，需要那个提出该脚本的人来测试了，你可以在那个 issue 下问问他。

哈哈，移植到我的模板上这些事情，得我来。

我看看能不能整点马甲号，不过，这有点不太好。
还有就是就得关掉脚本，等到今天凌晨或者明天，这些网站都没签到再测试修改这个类型的网站了。

**Comment by yi-Xu-0100** [comment]
ok，完成更新的话，就直接关闭这个 issue 吧~

**Comment by miiwu** [comment]
> ok，完成更新的话，就直接关闭这个 issue 吧～

莫得问题，还希望大佬之后，还可以继续多多关注，多提提意见啊。😆

**Comment by yi-Xu-0100** [comment]
不是大佬，普通爱好者，前段时间看了Javascript 的语法，还在学习中，我们互相探讨学习~😄

**Comment by miiwu** [comment]
没问题😉

**Comment by miiwu** [comment]
@yi-Xu-0100 改好了，你用 [`dev`](https://github.com/miiwu/sspanel.soulsign/blob/dev/application/discuz.k.js) 里面的试试看，若是没问题，我就在脚本站更新了

**Comment by yi-Xu-0100** [comment]
还是有点小问题，当前对于我这种因为没有权限的的情况，会返回：您所在的用户组不允许使用，这个是提取的信息。

但是返回结果是以绿色，也就是成功签到返回的。没有提示错误啥的。

**Comment by miiwu** [comment]
> 但是返回结果是以绿色，也就是成功签到返回的。

这个简单，判断让这个情况 `.code` 返回非零，就行了。

改了一下，还是 dev，现在看看嘞？

**Comment by yi-Xu-0100** [comment]
最新版没有问题了，提交后可以直接关闭这个 issue 了~

**Comment by miiwu** [comment]
好，脚本站也好了，记得更新呀。

**Comment by miiwu** [comment]
> 最新版没有问题了，提交后可以直接关闭这个 issue 了～

@yi-Xu-0100 
嘿，哈哈，我又改了，还是 [`dev`](https://github.com/miiwu/sspanel.soulsign/blob/dev/application/discuz.k.js)，要不要再试试？
我把他放关键字里了，也改了 [`mmc.js`](https://github.com/miiwu/sspanel.soulsign/blob/dev/core/mmc.js)。

这个，脚本站还没更新。

**Comment by yi-Xu-0100** [comment]
感觉给了太多的设置，需要自定义的太多。

而且默认获取的信息都是正确输出，可能用户会忽视掉可能的错误信息，总不能每次都盯着有没有错误吧。

当前状况，无权限使用在未设置关键词的情况下，默认输出该信息，但是反馈为绿色通过状态，容易忽视。

**Comment by miiwu** [comment]
> 感觉给了太多的设置，需要自定义的太多。
> 
> 而且默认获取的信息都是正确输出，可能用户会忽视掉可能的错误信息，总不能每次都盯着有没有错误吧。
> 
> 当前状况，无权限使用在未设置关键词的情况下，默认输出该信息，但是反馈为绿色通过状态，容易忽视。

啊，叫 `无权限` 啊，我以为是 `无法xx` 来着，那就指定 `无`，这个关键词吧

确实给太多自由，可能也会混乱呀。
不过，我想着，默认一般填填域名，是可以用的，除非遇到不能用的情况，可以配置配置。

不过，签到成功的消息可能也是五花八门的，可能相对来说少一点，那不然改成白名单，像之前那样？
现在遇到的来看，还是过滤 `无` 这个黑名单简单点。
![image](https://user-images.githubusercontent.com/42897857/90472662-a087a200-e153-11ea-9646-2e5d10ec94f9.png)

**Comment by yi-Xu-0100** [comment]
> 返回数据如下：
> 
> ```
> <?xml version="1.0" encoding="gbk"?>
> <root><![CDATA[您所在用户组不允许使用]]></root>
> ```

我的说法问题…… 信息如上，没有关键词 `无`。
因为成功信息，你适配的时候肯定会测试，确实是否能够，不可用的就适配一下，可以不需要用户操心。
而莫名的错误信息有可能你也不知道是啥样，用户也没注意到的话，就可能错过。

**Comment by miiwu** [comment]
> 我的说法问题…… 信息如上，没有关键词 `无`。
> 因为成功信息，你适配的时候肯定会测试，确实是否能够，不可用的就适配一下，可以不需要用户操心。
> 而莫名的错误信息有可能你也不知道是啥样，用户也没注意到的话，就可能错过。

我明白了，那就白名单吧，凡是不对的，都按错的来。
如果本身对的，误判了，那就手动配置一下关键字。
不过我觉得这个可以忽略，特立独行改插件的网站没几个。

马上改好了，等一下，在测试。

**Comment by miiwu** [comment]
@yi-Xu-0100 好了，帮我看看有毛病不

**Comment by yi-Xu-0100** [comment]
是以 dev 中的为准是吗？dev 中的感觉没问题

**Comment by miiwu** [comment]
> 是以 dev 中的为准是吗？dev 中的感觉没问题

是的，就是 `dev`。
没问题嘛？
那我更新到脚本站去了。

**Comment by yi-Xu-0100** [comment]
ok，该 issue 暂时关闭，其他问题再开 issue 再说吧。
