### ISSUE TITLE
日志页面 `UI` 美化问题

### ISSUE THREAD

**Issue by miiwu** [Miao-Mico/sspanel.soulsign#4]
承接上一个 [`Issue`](https://github.com/miiwu/sspanel.soulsign/issues/3)。

**Comment by miiwu** [comment]
JSON View: [vue-json-view](https://zhaoxuhui1122.github.io/vue-json-view/)

**Comment by miiwu** [comment]
@yi-Xu-0100 

如此甚好

- - -

![image](https://user-images.githubusercontent.com/42897857/91325027-4d69bb00-e7f5-11ea-957b-6ab46367c501.png)

- - -

![image](https://user-images.githubusercontent.com/42897857/91324656-e1875280-e7f4-11ea-80b6-c2ed23f97468.png)

![image](https://user-images.githubusercontent.com/42897857/91324861-1eebe000-e7f5-11ea-8e4e-9549c081236b.png)

- - -

不过，仍然有个毛病，点击链接之后，表会觉得被点击了，自动展开。

**Comment by miiwu** [comment]
对于提示，整了半天，还是这样吧；

![image](https://user-images.githubusercontent.com/42897857/91332211-6c207f80-e7fe-11ea-8e57-7fd77032401c.png)

**Comment by yi-Xu-0100** [comment]
> 点击链接之后，表会觉得被点击了，自动展开。

https://www.cnblogs.com/dch0/p/12091661.html

这种能够解决的，搜索的话，很多，可以看看参考一下

**Comment by miiwu** [comment]
> 这种能够解决的，搜索的话，很多，可以看看参考一下

嗯嗯，用的 `Vue 组件`，我瞅瞅能不能用这个方法。

- - -

最新版，试了吗？
说说感觉。

- - -

还有那个 `package.json` 问题。
似乎是直接从网站下载下来的部分资源文件文件 `.png/js/css` 等的，我猜可能给覆盖掉了。

**Comment by yi-Xu-0100** [comment]
你开发的最新版吗？
作者的自动更新我感觉还不太完善，暂时没有更新

**Comment by miiwu** [comment]
> 你开发的最新版吗？

是的

**Comment by yi-Xu-0100** [comment]
https://www.csdn.net/gather_23/MtTaAgxsNTUzNy1ibG9n.html

 Vue 应该有自己的语法，你可以找找，你开发的还是 pull.dev 分支吗？

**Comment by miiwu** [comment]
> Vue 应该有自己的语法，你可以找找，你开发的还是 pull.dev 分支吗？

找到了，再试；

一直会是这个，如果不特殊说明。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91372552-7ebea700-e846-11ea-8983-d27cc8b72314.png)

感觉挺好的，为啥有两个自定义复制按钮……

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91372552-7ebea700-e846-11ea-8983-d27cc8b72314.png)
> 
> 感觉挺好的，为啥有两个自定义复制按钮……

因为去掉右边那个，复制就不是居中了；
我还改不到中间去。

出此下策。

**Comment by miiwu** [comment]
> > Vue 应该有自己的语法，你可以找找
> 
> 找到了，再试；

已解决；

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91372552-7ebea700-e846-11ea-8983-d27cc8b72314.png)

那个提示信息，提示框是不是有点多？

你觉得呢？

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91372788-32279b80-e847-11ea-8ceb-c3decb210168.png)

把这三个放到一行上去，复制放右边，按钮放左边。 反正同时出现和消失，按钮和选项的效果类似，所以放左边，完成选择后，一般也是点击右边，所以复制放右边。

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91372788-32279b80-e847-11ea-8ceb-c3decb210168.png)
> 
> 把这三个放到一行上去，复制放右边，按钮放左边。 反正同时出现和消失，按钮和选项的效果类似，所以放左边，完成选择后，一般也是点击右边，所以复制放右边。

喔喔，感觉我又局限了。

可以试试。

**Comment by yi-Xu-0100** [comment]
提示框的话，我感觉域名和信息的提示框没必要，还是用的很少，可以直接设置为 title，悬停一段时间的话，自动就会显示了，算是小提示，说明还是得放在 readme 文件中，作为特殊需要，毕竟是兼容前面的，可以说成高级返回信息的功能，但是该格式，对之前的版本的扩展不支持，这个需要强调，感觉大多数人还在用商店的版本……

![image](https://user-images.githubusercontent.com/25523606/91372994-cdb90c00-e847-11ea-8af8-f864c55081ae.png)


![image](https://user-images.githubusercontent.com/25523606/91372988-c8f45800-e847-11ea-9326-22775b12823c.png)


最上面的给用户的，用这个提示框感觉好一点，碰到的话，就能知道。

**Comment by miiwu** [comment]
> 提示框的话，我感觉域名和信息的提示框没必要，还是用的很少，可以直接设置为 title

这个 `title` 有什么区别呀？
触发时间吗？ 

> 用这个提示框感觉好一点，碰到的话，就能知道。

你的意思是给每个链接加上出自那里？

一般不应该在表头表示出自哪里吗？

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91374446-d0693080-e84a-11ea-95e3-0266bca23495.png)

感觉这两个没必要出现的那么敏感，不是太多人需要这个提示，主要是开发者，应该作为 title，这样不会鼠标滑过就出来，可在readme 中给出说明。

第一个可以保留。

**Comment by miiwu** [comment]
> 感觉这两个没必要出现的那么敏感，不是太多人需要这个提示，主要是开发者，应该作为 title，这样不会鼠标滑过就出来，可在 readme 中给出说明。

嗯嗯，还是时间敏感度问题呀，我知道了。

**Comment by yi-Xu-0100** [comment]
其实，感觉作为产品来说，没有内部给出如何设置的提示，这个应该只在说明文档中给出……你也可以直接去掉这两个。

如果开发者有需求，应该会去找 readme 看看的。不然靠猜开发也太狠了吧🤪

**Comment by miiwu** [comment]
> 其实，感觉作为产品来说，没有内部给出如何设置的提示，这个应该只在说明文档中给出…… 你也可以直接去掉这两个。
> 
> 如果开发者有需求，应该会去找 readme 看看的。不然靠猜开发也太狠了吧🤪

那就不要了。

这个需求好像刚开始是你提的。🤪
哈哈哈。

**Comment by yi-Xu-0100** [comment]
刚开始也没有文档啊~😀

更新的时候，readme 也添加一下说明就好~

**Comment by miiwu** [comment]
> 刚开始也没有文档啊～😀
> 
> 更新的时候，readme 也添加一下说明就好～

我看你功不可没，你来如何写文档如何？

**Comment by miiwu** [comment]
> 把这三个放到一行上去，复制放右边，按钮放左边。 反正同时出现和消失，按钮和选项的效果类似，所以放左边，完成选择后，一般也是点击右边，所以复制放右边。

搞不对称就很难受，看着不舒服。

![image](https://user-images.githubusercontent.com/42897857/91375829-41f6ae00-e84e-11ea-9373-b14fdca0d434.png)

- - -

所以暂时采用原来的。

**Comment by miiwu** [comment]
> 搞不对称就很难受，看着不舒服。

这开关怎么搞都暂时跟按钮配合不了；
所以我试试把开关改成按钮。

**Comment by yi-Xu-0100** [comment]
```
### 新版消息日志配置

标准输出格式示例：

1. 签到成功
    ``` json
    {
        "domain": "www.example.com", 
        "url": "https://www.example.com/", 
        "summary": "签到成功", 
        "message": "获得 1 积分", 
        "log": {
            "data": "some_data", 
            "param": {
                "param1": 1, 
                "param2": "some_string"
            }
        }, 
        "errno": false
    }
    ```

2. 签到失败
    ``` json
    {
        "domain": "www.example.com", 
        "url": "https://www.example.com/login", 
        "summary": "签到失败", 
        "message": "未登录", 
        "log": {
            "data": "some_data", 
            "param": {
                "param1": 1, 
                "param2": "some_string"
            }
        }, 
        "errno": true
    }
    ```
说明：

1. 新版 `细节/日志` 的输出为 json 数据格式，在旧版本插件中无法使用。
2. 旧版本输出的字符串在新版本插件中会自行转换为 json 格式以适配，所以不用担心报错。
3. `细节/日志` 中的域名显示为 `domain` 的内容，点击跳转的链接由 `url` 决定。
4. `summary` 的内容会显示在 `options.html` 的执行结果中，`message` 的内容会显示在 `细节/日志` 中的消息中。
5. `log` 的内容完全由脚本内部定义，具体需要输出的参数或内容可能包含个人信息，所以不会被默认可复制。
6. `errno: true` 则表示签到失败，执行结果和消息的颜色会为红色，`errno: true` 则表示签到成功，执行结果和消息的颜色会为绿色。
4. 在 `细节/日志` 页面可以选择分域名复制，默认可复制的信息中有 `domain`, `url`, `message`, `errno` 。其他信息需要用户自行开启选项，添加后复制。
```

### 新版消息日志配置

标准输出格式示例：

1. 签到成功
    ``` json
    {
        "domain": "www.example.com", 
        "url": "https://www.example.com/", 
        "summary": "签到成功", 
        "message": "获得 1 积分", 
        "log": {
            "data": "some_data", 
            "param": {
                "param1": 1, 
                "param2": "some_string"
            }
        }, 
        "errno": false
    }
    ```

2. 签到失败
    ``` json
    {
        "domain": "www.example.com", 
        "url": "https://www.example.com/login", 
        "summary": "签到失败", 
        "message": "未登录", 
        "log": {
            "data": "some_data", 
            "param": {
                "param1": 1, 
                "param2": "some_string"
            }
        }, 
        "errno": true
    }
    ```
说明：

1. 新版 `细节/日志` 的输出为 json 数据格式，在旧版本插件中无法使用。
2. 旧版本输出的字符串在新版本插件中会自行转换为 json 格式以适配，所以不用担心报错。
3. `细节/日志` 中的域名显示为 `domain` 的内容，点击跳转的链接由 `url` 决定。
4. `summary` 的内容会显示在 `options.html` 的执行结果中，`message` 的内容会显示在 `细节/日志` 中的消息中。
5. `log` 的内容完全由脚本内部定义，具体需要输出的参数或内容可能包含个人信息，所以不会被默认可复制。
6. `errno: true` 则表示签到失败，执行结果和消息的颜色会为红色，`errno: true` 则表示签到成功，执行结果和消息的颜色会为绿色。
4. 在 `细节/日志` 页面可以选择分域名复制，默认可复制的信息中有 `domain`, `url`, `message`, `errno` 。其他信息需要用户自行开启选项，添加后复制。

**Comment by yi-Xu-0100** [comment]
你可以看下，有什么问题，或者需要修改的，没什么问题的话，加到你需要提交的版本的 readme 中。

**Comment by miiwu** [comment]
> 你可以看下，有什么问题，或者需要修改的，没什么问题的话，加到你需要提交的版本的 readme 中。

欧克，我想着是你在我之后 `pull` 呢；
加到我这里也行。

- - - 

怎么样，哈哈哈，我觉得舒爽多了。

![image](https://user-images.githubusercontent.com/42897857/91378806-e7f8e700-e853-11ea-9b32-bdafaa0634ec.png)

- - -

@yi-Xu-0100 已更新，可以下载来看看了。

`readme` 还没更新，马上来。

**Comment by yi-Xu-0100** [comment]
左边的是啥图标……

--- 
直接不要这个按钮如何，

![image](https://user-images.githubusercontent.com/25523606/91380607-ef21f400-e857-11ea-9c5a-00ce7a3990c2.png)

像这样，下面这一栏直接显示出来，也知道到底复制的啥。

**Comment by miiwu** [comment]
> 左边的是啥图标……

过滤呀；
不行换个。

> 像这样，下面这一栏直接显示出来，也知道到底复制的啥。

喔喔，理解错了；
这样可有，嗯嗯，感觉可以有。

**Comment by miiwu** [comment]
> 像这样，下面这一栏直接显示出来，也知道到底复制的啥。

如果不展开，不读文档；
我感觉用户并看不懂这是啥意思吧？

我感觉默认隐藏也没问题。

**Comment by yi-Xu-0100** [comment]
只有需要复制的时候，这两行会出现，告诉用户复制的什么，平常也看不到。
我指的直接显示出来是只有选择条目之后才会直接显示，以前会需要多点一下按钮。

**Comment by miiwu** [comment]
> 我指的直接显示出来是只有选择条目之后才会直接显示，以前会需要多点一下按钮。

我懂；

我觉得平常不需要看到这么多信息。
也不是每次复制都需要配置，大多数时候不需要配置。

除非开发者要求额外的信息，
告知用户，
用户才需要点击配置。

**Comment by yi-Xu-0100** [comment]
感觉用户很少看 readme 的配置部分，所以可能都不知道复制的是啥，显示出来也算是告知吧。

**Comment by miiwu** [comment]
> 感觉用户很少看 readme 的配置部分，所以可能都不知道复制的是啥，显示出来也算是告知吧。

不需要知道过程呀；

复制完，不管粘贴到哪里，肯定得看看粘贴出来的是什么吧？
要是真莽得不行，真不看，一套操作下来，谁也救不了。

- - -

我觉得就算直接展示出来，用户可能也看不懂 `domain` 等的是什么意思。
这不就变成信息泛滥了吗？

一般也不需要知道，弄明白还可能浪费精力；
到了开发者需要额外反馈的时候，再弄明白就可以了，我觉得这就是默认的意义。

- - -

@yi-Xu-0100 readme 更新了，你看看有没有不妥的地方。

**Comment by miiwu** [comment]
> > 左边的是啥图标……
> 
> 过滤呀；
> 不行换个。

这个看着怎么样，我觉得应该挺好认了吧。

![image](https://user-images.githubusercontent.com/42897857/91388133-4bd9da80-e869-11ea-9cc9-97220ba47161.png)

[可以在这里找](https://material.io/resources/icons/?search=setting&icon=filter_4&style=baseline)

**Comment by yi-Xu-0100** [comment]
还记得我第一次问你，应该默认复制不加入 log 吗？

当时我是第一次看到那个界面，没有说明（我想用户很少看说明，除非真不会操作了），点了条目展开后，可看到树结构，然后选择条目后，会有按钮和复制，我的第一反应是复制的是所有树结构，按钮不太懂，点开按钮后，看到可删除，但我还是没有意识到你做的默认不选择log优化。

个人对这个复制信息有点敏感，我希望给我剪贴板写的东西都是我明确知道的，而不是等我粘贴的时候，去查看的时候才知道。
默认最后一行显示，告诉我两个信息，1.哪些被复制，2.我可以直接删除部分信息。

直接显示出来的视觉感官对我来说是直接的，我看到就知道功能，也没有多需要去研究什么。就像是复制按钮，看到我就明白是复制信息，选择条目出来复制按钮，应该是复制条目的信息，反而，那个按钮我只有点击了我才知道是干什么的，也才知道原来不是复制全部的信息，甚至我可以有更好的选择去挑选部分信息。

我想这个行直接展示，本身体积不是特别大，信息视觉上就知道是啥功能，也只有在反馈时出现，基本来说不打扰。

**Comment by miiwu** [comment]
> 还记得我第一次问你，应该默认复制不加入 log 吗？
> 
> 当时我是第一次看到那个界面，没有说明（我想用户很少看说明，除非真不会操作了），点了条目展开后，可看到树结构，然后选择条目后，会有按钮和复制，我的第一反应是复制的是所有树结构，按钮不太懂，点开按钮后，看到可删除，但我还是没有意识到你做的默认不选择 log 优化。
> 
> 个人对这个复制信息有点敏感，我希望给我剪贴板写的东西都是我明确知道的，而不是等我粘贴的时候，去查看的时候才知道。
> 默认最后一行显示，告诉我两个信息，1. 哪些被复制，2. 我可以直接删除部分信息。
> 
> 直接显示出来的视觉感官对我来说是直接的，我看到就知道功能，也没有多需要去研究什么。就像是复制按钮，看到我就明白是复制信息，选择条目出来复制按钮，应该是复制条目的信息，反而，那个按钮我只有点击了我才知道是干什么的，也才知道原来不是复制全部的信息，甚至我可以有更好的选择去挑选部分信息。
> 
> 我想这个行直接展示，本身体积不是特别大，信息视觉上就知道是啥功能，也只有在反馈时出现，基本来说不打扰。

那么我们就全都要。

在顶部弹出的消息里加上提示复制了那些内容就好啦。

如何，哈哈。

**Comment by yi-Xu-0100** [comment]
感觉弹出消息还是尽可能地少，简洁。毕竟只是一段时间就消息，容易错过。

我觉得，大多数的效果应该是，视觉提醒操作上如何做，操作的效果是什么。毕竟这个不是大型软件，需要操作手册啥的才能玩的起来。

**Comment by yi-Xu-0100** [comment]
甚至弹出消息都可以省略，
用指向条目的时候，当前条目会有颜色加深（可以让鼠标变成手指的那种鼠标样式）来表明条目可点击。
域名可点击，悬浮在上面会变蓝色和加下划线。

当前这些，我觉得就足够反应出操作应该是什么样的了。

**Comment by miiwu** [comment]
> 感觉弹出消息还是尽可能地少，简洁。毕竟只是一段时间就消息，容易错过。
> 
> 我觉得，大多数的效果应该是，视觉提醒操作上如何做，操作的效果是什么。毕竟这个不是大型软件，需要操作手册啥的才能玩的起来。

嗯嗯，但是我还是不太喜欢看到选项。

- - -

要不就先这样吧，你都实现了，也可以后来再 `pull` 上去。

**Comment by yi-Xu-0100** [comment]
ok，那得很久了……

**Comment by miiwu** [comment]
> ok

我刚刚又更新了，这次用了最新的 `pckage.json`。

在 [`soulsign@pull.dev.fix`](https://github.com/miiwu/soulsign-chrome/tree/pull.dev.fix) 你看看 `readme`，试试其他的。

<details>
<summary>version 测试案例</summary>

```javascript

exports.run = async function(param, version) {
    console.log(await version("2"));
    console.log(await version("2.0.5"));
    console.log(await version("2.0.5.5"));
    console.log(await version("2.1.5"));
    console.log(await version("2.1.0"));
    return "version checked";
};

```

</details>

**Comment by yi-Xu-0100** [comment]
新版本对旧版本的 string 类型输出是否有兼容?

**Comment by miiwu** [comment]
> 新版本对旧版本的 string 类型输出是否有兼容？

**`兼容`** 一直都为第一要义呀。

哪个版本应该都没出现过不兼容的情况吧？

**Comment by yi-Xu-0100** [comment]
> errno: false, // 成功 ? 0 | false : >=1 | true 

这个解释没看懂，是指 0 是 就是false，>=1 是true吗？那 <0 呢？

**Comment by miiwu** [comment]
> > errno: false, // 成功？0 | false : >=1 | true
> 
> 这个解释没看懂，是指 0 是 就是 false，>=1 是 true 吗？那 <0 呢？

小于零也是失败；

喔喔，这个就写成 `!= 0` 吧

**Comment by yi-Xu-0100** [comment]
主要上面的脚本开发的示例的模板中，输出是 string ，但是下面有给出日志配置，可能不太明确日志配置在哪里完成的。

**Comment by miiwu** [comment]
> 主要上面的脚本开发的示例的模板中，输出是 string ，但是下面有给出日志配置，可能不太明确日志配置在哪里完成的。

那贴个图片，指一指；

**Comment by miiwu** [comment]
> > > errno: false, // 成功？0 | false : >=1 | true
> > 
> > 
> > 这个解释没看懂，是指 0 是 就是 false，>=1 是 true 吗？那 <0 呢？

`|` 一般在编程语言里不是 `或` 吗？

`?:` 三目运算符。

我这样想的。

**Comment by yi-Xu-0100** [comment]
```
errno: false, // errno != 0 ？ture ：false
```

这样？话说，这个errno，不应该直接指定为 true 或者 false 吗？为啥还可以设置为其他值？或者说，应该这样：

```
errno: 1, // errno != 0 ？失败 : 成功
```

errno 默认是数字类型，而且只有为 0 的时候是成功。

**Comment by yi-Xu-0100** [comment]
我看懂你的兼容模式的意思了，是指没有备注的 string 会被转化为注释掉的那个部分的 json 对吧，加一句说明吧。

``` js
"签到成功"
// 上述旧版本脚本返回的字符串会被转换为下面的 json 格式。
// {
//     summary: "签到成功",
//     detail: [
//         {
//             domain: @domain[0],
//             url: @loginUrl,
//             message: "签到成功",
//             errno: throw ? true : false,
//         },
//     ],
// }
```

**Comment by miiwu** [comment]
> ```
> errno: false, // errno != 0 ？ture ：false
> ```
> 
> 这样？话说，这个 errno，不应该直接指定为 true 或者 false 吗？为啥还可以设置为其他值？

![image](https://user-images.githubusercontent.com/42897857/91411907-97957f80-e87b-11ea-903d-99f85773cab2.png)

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/42897857/91411907-97957f80-e87b-11ea-903d-99f85773cab2.png)

emmmm...

灰色不太行，换掉吧。

- - -

> 我看懂你的兼容模式的意思了，是指没有备注的 string 会被转化为注释掉的那个部分的 json 对吧，加一句说明吧。
> 
> ```js
> "签到成功"
> // 上述旧版本脚本返回的字符串会被转换为下面的 json 格式。
> // {
> //     summary: "签到成功",
> //     detail: [
> //         {
> //             domain: @domain[0],
> //             url: @loginUrl,
> //             message: "签到成功",
> //             errno: throw ? true : false,
> //         },
> //     ],
> // }
> ```

了解

**Comment by yi-Xu-0100** [comment]
emmm，有点眼花缭乱……

**Comment by miiwu** [comment]
> emmm，有点眼花缭乱……

当然这都是可选择的地方，不是必要的。

**Comment by miiwu** [comment]
> emmm，有点眼花缭乱……

我又又又更新了，还是 @pull.dev.fix

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91415490-b4808180-e880-11ea-94fe-d9953d32b170.png)

![image](https://user-images.githubusercontent.com/25523606/91415499-b6e2db80-e880-11ea-8b34-fc7b08578a9f.png)

**Comment by yi-Xu-0100** [comment]
discuz.k

**Comment by miiwu** [comment]
> discuz.k

这系列的都不太行了，我改了东西，马上改。

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91415490-b4808180-e880-11ea-94fe-d9953d32b170.png)

一般返回的对象，没有 `.summary` 会这样

> ![image](https://user-images.githubusercontent.com/25523606/91415499-b6e2db80-e880-11ea-8b34-fc7b08578a9f.png)

一般返回的对象，没有 `.detail.message` 会这样

- - -

我刚刚那个案例只是为了测试 `version` 的；

**Comment by miiwu** [comment]
我准备再引一个判断版本高低的 `JS` 库。

**Comment by miiwu** [comment]
@yi-Xu-0100 都已更新；

[soulsign@pull.dev.fix](https://github.com/miiwu/soulsign-chrome/tree/pull.dev.fix)
[sspanel@dev.detail](https://github.com/miiwu/sspanel.soulsign/tree/dev.detail)

**Comment by yi-Xu-0100** [comment]
试了下，感觉没问题

**Comment by miiwu** [comment]
> 试了下，感觉没问题

那我衍合一下，`pull` 上去了。
