### ISSUE TITLE
过滤适配网站

### ISSUE THREAD

**Issue by miiwu** [Miao-Mico/sspanel.soulsign#5]

**Comment by miiwu** [comment]
@yi-Xu-0100 

你提的过滤适配网站，马上到；

**Comment by miiwu** [comment]
@yi-Xu-0100 

[已更新；](https://github.com/miiwu/sspanel.soulsign/tree/dev.detail)

![image](https://user-images.githubusercontent.com/42897857/91447549-6634a800-e8ab-11ea-8dcd-122128f5e04b.png)

**Comment by miiwu** [comment]
我忽然发现脚本好像到第 10 个就不弹 `日志页面` 了；
我看看咋回事。

**Comment by miiwu** [comment]
> 我忽然发现脚本好像到第 10 个就不弹 `日志页面` 了；
> 我看看咋回事。

哈哈，bug，正则表达式的问题；
修好了，在 [`pull`](https://github.com/miiwu/soulsign-chrome/tree/pull) 分支。

**Comment by miiwu** [comment]
@yi-Xu-0100 
兄弟，你有空看看吧，还是 [dev.detail](https://github.com/miiwu/sspanel.soulsign/tree/dev.detail)；
这个检测不兼容的部分。

**Comment by yi-Xu-0100** [comment]
？你是修改的插件内容去过滤这个问题的？

**Comment by miiwu** [comment]
> ？你是修改的插件内容去过滤这个问题的？

~~对啊，不然没想到好办法。~~
嗯？没有修改插件内容啊，改的脚本内容。

后面可能会识别 404 等的。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91787496-9e860e80-ec3c-11ea-8fad-bccd4f93662d.png)

这里有个问题

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91787496-9e860e80-ec3c-11ea-8fad-bccd4f93662d.png)
> 
> 这里有个问题

这是啥情况下的，我的没问题。

**Comment by yi-Xu-0100** [comment]
而且被判定为成功。

![image](https://user-images.githubusercontent.com/25523606/91787595-d42af780-ec3c-11ea-8a8f-6417128e6589.png)

**Comment by miiwu** [comment]
> 而且被判定为成功。
> 
> ![image](https://user-images.githubusercontent.com/25523606/91787595-d42af780-ec3c-11ea-8a8f-6417128e6589.png)

嗯？正则问题？

我本地测试别的域名没问题，你从新加载以下。

可能 `mmc.dev` 没更新。

**Comment by yi-Xu-0100** [comment]
插件吗？我是刚更新的最新版

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91787734-1ce2b080-ec3d-11ea-93cb-10647da9ab9d.png)

判断域名应该没有问题

**Comment by miiwu** [comment]
> 插件吗？我是刚更新的最新版

重新加载插件，会更彻底从新加载脚本。

~~我先本地试试，昨天没问题的，难道我又懵逼改错了？~~
还真是；
等会，我再更新一下。

**Comment by miiwu** [comment]
@yi-Xu-0100 
这次没问题了;
还是 [dev.detail](https://github.com/miiwu/sspanel.soulsign/tree/dev.detail)；

![image](https://user-images.githubusercontent.com/42897857/91788397-aba3fd00-ec3e-11ea-8365-4c82e5221525.png)

- - -

确实该重构一下了，我有时候都写混了。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91788818-c62aa600-ec3f-11ea-9d41-e8158f4ab2e1.png)

是否应该有默认推送消息，而且这个我应该签过到了。

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91788818-c62aa600-ec3f-11ea-9d41-e8158f4ab2e1.png)
> 
> 是否应该有默认推送消息，而且这个我应该签过到了。

chinafix.com 是 DC；
这个 `推送签到信息失败` 是咋回事，你登录 pinggu.org 了吗，我感觉应该是不在线呀。

- - -

现在的毛病是真多啊。

**Comment by yi-Xu-0100** [comment]
第一个是测试，不用管。
第二个是在线的，而且是签到过的。

![image](https://user-images.githubusercontent.com/25523606/91789312-fcb4f080-ec40-11ea-86c3-cf19c9b04391.png)

**Comment by miiwu** [comment]
> 第一个是测试，不用管。
> 第二个是在线的，而且是签到过的。
> 
> ![image](https://user-images.githubusercontent.com/25523606/91789312-fcb4f080-ec40-11ea-86c3-cf19c9b04391.png)

log 看看，`推送签到信息失败` 出现的话，肯定是`在线的`，问题出在识别是否已签到，和推送信息；

你把 /(您上次签到时间:)<[^>]*>([^<]*)/ 这段正则表达式包括的 log ，我看看，就那一小段就行；
如果没有这一段，那就是后面推送签到的问题了。

**Comment by yi-Xu-0100** [comment]
匹配不到，关键词有误。

![image](https://user-images.githubusercontent.com/25523606/91790856-4ce18200-ec44-11ea-8865-520d1592ada6.png)


没有 **`您`** 这个字的话，匹配如下

![image](https://user-images.githubusercontent.com/25523606/91790209-c6787080-ec42-11ea-847b-e168d63e5a3b.png)

**Comment by miiwu** [comment]
> 匹配不到，关键词有误。

如果匹配不到，就会认定是未签到的；
所以是推送时候的问题。
有 log 的第二项吗?

> 没有 **`您`** 这个字的话，匹配如下

嗷嗷，`/(您上次签到时间:)<[^>]*>([^<]*)/` 是这个，刚复制，我怎么把 `*` 漏掉了。

**Comment by miiwu** [comment]
把第一张图改掉吧，里面有你用户名。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91790921-6edb0480-ec44-11ea-8ec0-dbd3ab91e239.png)

**Comment by miiwu** [comment]
啊，果然出问题了。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91791003-a3e75700-ec44-11ea-9e5c-49fcbe7fa267.png)

**Comment by miiwu** [comment]
嗯嗯，正则表达式这个就是这样，
所以我让 `消息栏` 支持 `html`，屏蔽掉部分元素。
也不能全部概括。

过会我看看给你这个适配一下;
你把这一段 `html` 抠出来。

我再排查，大佬先去忙。

- - -

还有之前哪个有用户名的图片，最好删掉最后一次修改之前的修改。

**Comment by miiwu** [comment]
@yi-Xu-0100 
在 `hook.post` 里的 `catch` 那里改成这个，
`return { code: 1, data: exception};`
看看返回啥？
是 `formhash` 还是 `data` 其他的啥。

- - -

是推送的时候发生异常了。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91792313-d5aded00-ec47-11ea-8362-a92367528451.png)

**Comment by miiwu** [comment]
嗯？异常还是空的？很奇怪。
那把 `code` 改成 `5`，再试试，如果还不行，那就只能我自己慢慢找了。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91792878-2ffb7d80-ec49-11ea-9579-065fe9429b8b.png)

**Comment by miiwu** [comment]
好吧，我服气了，为啥 `catch` 到的 `exception` 传递不出来。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91793368-8fa65880-ec4a-11ea-8e9d-c2ec6bc0a8ce.png)

控制台有输出

**Comment by miiwu** [comment]
> 控制台有输出

大帮助，那就是 `formhash` 没匹配到了。

我没写 `exception.message` 怕没有 `message`，谁知道竟然输出不了 `exception`，尴尬。

**Comment by yi-Xu-0100** [comment]
感觉是 json 的库对这个处理了？不太确定

**Comment by miiwu** [comment]
> 感觉是 json 的库对这个处理了？不太确定

有可能，我只知道 `JSON` 会干掉 `function`，这个还真不了解；

之后我更新就改成 `exception.message` 应该就好了。

**Comment by yi-Xu-0100** [comment]
可能 exception 返回的是一个 object ，无法放入 json 中，它就舍去了

**Comment by miiwu** [comment]
> 可能 exception 返回的是一个 object ，无法放入 json 中，它就舍去了

`object` 的话，我觉得 `JSON` 应该会处理的；
可能哪里还有啥独特的地方；或者我的用法不太对。

**Comment by miiwu** [comment]
正则表达式太难写了，暂时这样吧；
`/本月已累计签到:[^p]*\/p>[^p]*p>(.*上次签到时间:.*)<\/p>/`
~~`/(您上次签到时间:)<[^>]*>([^<]*)/`~~ 按原来的这个它不会签到。
要么就直接舍弃，不判断是否已签签到，直接推送。

![image](https://user-images.githubusercontent.com/42897857/91796973-07c54c00-ec54-11ea-90d5-54a110bda50a.png)

- - -

`formhash` 下午再修。

**Comment by miiwu** [comment]
@yi-Xu-0100 
你能把你那边的每个 `formhash` 周围的字符串贴上来吗？
**记得把 `formhsh` 的内容改掉，
比如 ` <input type="hidden" name="formhash" value="12345678">`**

**在这之前，在 `hook.post` 开头，`console.log` 一下 `data` 是不是跟 `log[0]` 一样，确认是 `formhash` 正则匹配的问题。**

- - -

我这边是能正确匹配且推送的。
![image](https://user-images.githubusercontent.com/42897857/91797695-c897fa80-ec55-11ea-8d3c-ccb2cbd4b329.png)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91821090-fcc8e680-ec68-11ea-82ce-8cdda165b045.png)

input 标签就这几个，全文没有找到 formhash 

![image](https://user-images.githubusercontent.com/25523606/91821692-50d3cb00-ec69-11ea-8973-d43307394082.png)

找不到你说的这个 hook.post。
直接提供新的脚本内容给我测试吧。

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91821090-fcc8e680-ec68-11ea-82ce-8cdda165b045.png)
> 
> input 标签就这几个，全文没有找到 formhash 

嗯？那肯定会出错，因为没有 `formhash` ，后面取 `formhash[1]` 一定会异常呀。

**Comment by miiwu** [comment]
> 找不到你说的这个 hook.post。

就是 `discuz` 里的 `.post_sign_in`，
我说的问题。

**Comment by yi-Xu-0100** [comment]
这里？还是建议直接给完整测试脚本，我这边复制验证一些

![image](https://user-images.githubusercontent.com/25523606/91823755-4e26a500-ec6c-11ea-8807-eb6ecf60ab39.png)

上面的情况，控制台因为前面的报错会直接跳出，无法给出data

**Comment by miiwu** [comment]
> 上面的情况，控制台因为前面的报错会直接跳出，无法给出 data

`.post_sign_in` 的开头，`data` 应该是和 `log[0]` 是一致的，看看里面有没有 `formhash`。

要是没有，就很难办了，跟我这边不一样，不好测试。

**Comment by yi-Xu-0100** [comment]
一样的，没有 formhash ，和我前面发的一样的情况。

**Comment by miiwu** [comment]
> 一样的，没有 formhash ，和我前面发的一样的情况。

哈?

那直接访问 `view-source:https://bbs.pinggu.org/plugin.php?id=dsu_paulsign:sign` 呢？

![image](https://user-images.githubusercontent.com/42897857/91827116-035b5c00-ec71-11ea-8b26-6eb7ea67b805.png)

- - -

难道发帖的和没发帖的网页不一样？

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91827587-9d230900-ec71-11ea-9764-9e0d896f9b91.png)

**Comment by miiwu** [comment]
啊？当真不一样啊。

- - -

不应该呀， `discuz` 系列一般都有这个，难道说魔改了？

不过我这边就有，不知道为啥。
还有可能，签过到的就没有 `formhash` 了，只是针对这一个网站，我本地看另一个签过到的 DSU 网站一直都有。

**Comment by miiwu** [comment]
@yi-Xu-0100 
你用这个试试看，正常的话，告诉我一声，`console.log` 一下 `formhash`。
[人大经济论坛](https://soulsign.inu1255.cn/script/hithy123/%E4%BA%BA%E5%A4%A7%E7%BB%8F%E6%B5%8E%E8%AE%BA%E5%9D%9B)

**Comment by yi-Xu-0100** [comment]
emmm。我一直使用这个签到的。

**Comment by miiwu** [comment]
> emmm。我一直使用这个签到的。

能匹配到 `formhash`?
如果可以的话，我直接改 `path` 就行了。

- - -

`plugin.php?id=dsu_paulsign:sign&inajax=1` 填到 `登录路径` 上，跑一下。

![image](https://user-images.githubusercontent.com/42897857/91831726-ffcad380-ec76-11ea-878e-226b6c63be33.png)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91836958-16c0f400-ec7e-11ea-98d1-f98114792b9c.png)

这样？没有任何变化。感觉是签到后页面匹配不到 formhash

**Comment by miiwu** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/91836958-16c0f400-ec7e-11ea-98d1-f98114792b9c.png)
> 
> 这样？没有任何变化。感觉是签到后页面匹配不到 formhash

`formhash` 是从 `log_in` 的响应数据取的。

那你再跑一遍你原来用的那个，人大经济论坛？看看有没有到 `formhash` 那部分，能不能提取出来。

**Comment by yi-Xu-0100** [comment]
？那个签到过后，就直接返回"已经签到"，不会去匹配 formhash 了
``` js
    if (/已经签到/.test(data)) return "已经签到";
    var m = /name="formhash" value="([^"]+)/.exec(data);
```

**Comment by miiwu** [comment]
> ？那个签到过后，就直接返回 "已经签到"，不会去匹配 formhash 了
> 
> ```js
>     if (/已经签到/.test(data)) return "已经签到";
>     var m = /name="formhash" value="([^"]+)/.exec(data);
> ```

你就让他跑到，看看能不能取到。

如果不能，可以通过修改匹配是否已经签到，解决；

**Comment by yi-Xu-0100** [comment]
同样获取不到

**Comment by miiwu** [comment]
> 同样获取不到

嗯嗯，猜到了，签到完就没 `formhash` 了，现在确认了。

**Comment by miiwu** [comment]
> 同样获取不到

那个 `xxxxx@cda.pinggu.org` 邮箱怎么登录验证的，是得换邮箱吗？

![image](https://user-images.githubusercontent.com/42897857/91839802-3eb25680-ec82-11ea-9897-ac1c5805923f.png)

**Comment by yi-Xu-0100** [comment]
我的邮箱是我自己的，不是这种形式的

**Comment by miiwu** [comment]
> 我的邮箱是我自己的，不是这种形式的

哇，这个网址是最复杂繁琐的了，各种认证。

**Comment by miiwu** [comment]
@yi-Xu-0100 
本地测试没问题，你试试；
[soulsign@dev.detail](https://github.com/miiwu/sspanel.soulsign/tree/dev.detail)

把个性提醒还有自定义签到时说的话阉割了，
正则不好写，哈哈哈，
这个自定义可能也没几个人用。

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/91850090-960af380-ec8f-11ea-943a-6b57b9223104.png)
![image](https://user-images.githubusercontent.com/25523606/91850146-a7ec9680-ec8f-11ea-8f59-2926b64b22ab.png)
![image](https://user-images.githubusercontent.com/25523606/91850205-baff6680-ec8f-11ea-8de2-7a952f4719d5.png)

测试了一遍，应该没问题了

**Comment by miiwu** [comment]
> 测试了一遍，应该没问题了

嗯嗯，明天能正常签到的话，我就转到脚本站了。
