### ISSUE TITLE
迅维网https://www.chinafix.com/这个网站签到怎么设置和怎么运行这个脚本呢？

### ISSUE THREAD

**Issue by wifisky-feilian** [Miao-Mico/sspanel.soulsign#8]
迅维网https://www.chinafix.com/这个网站签到怎么设备和怎么运行这个脚本呢？

**Comment by miiwu** [comment]
> 迅维网 [https://www.chinafix.com/ 这个网站签到怎么设备和怎么运行这个脚本呢？](https://www.chinafix.com/% E8% BF%99% E4% B8% AA% E7% BD%91% E7% AB%99% E7% AD% BE% E5%88% B0% E6%80%8E% E4% B9%88% E8% AE% BE% E5% A4%87% E5%92%8C% E6%80%8E% E4% B9%88% E8% BF%90% E8% A1%8C% E8% BF%99% E4% B8% AA% E8%84%9A% E6%9C% AC% E5%91% A2% EF% BC%9F)

请尝试用 `soulsign` 安装[这个脚本](https://soulsign.inu1255.cn/scripts/229)。
