### ISSUE TITLE
不会用啊能给个具体的步骤怎么操作吗

### ISSUE THREAD

**Issue by yejinson** [Miao-Mico/sspanel.soulsign#9]
比如
https://www.hifini.com/  
https://dsdlove.com/
要怎么操作呢

**Comment by miiwu** [comment]
> 要怎么操作呢

- 可以先看是不是 `discuz!` 搭建的论坛；

  <details>
  <summary>以 https://dsdlove.com/ 为例：</summary>
  
  ![https://dsdlove.com/](https://user-images.githubusercontent.com/42897857/126671219-751ac95f-1214-40db-bb92-f2e0f5e31a9c.png)
  
  </details>

- 前往签到页面，然后观察浏览器地址栏中的的网站地址，来确定是哪一类签到；

  <details>
  <summary>以 https://www.hifini.com/ 为例：</summary>
  
  ![image](https://user-images.githubusercontent.com/42897857/126672070-da6e888e-33b3-4c4e-a1b3-50df44e0bd3b.png)

  现在这个仓库可能支持的有 ~~（好久没看了）~~ ：
  - k_misign
  - dc_signin
  - dsu_paulsign
  
  </details>

-  这里可能某些名词说的不专业，都是个人理解。

---

> https://www.hifini.com/

我们可以看到地址栏显示：https://www.hifini.com/sg_sign.htm
这个可能不适用

> https://dsdlove.com/

我们可以看到地址栏显示：https://dsdlove.com/plugin.php?id=dc_signin
这里面有个  `plugin.php?id=dc_signin`， 看到 `dc_signin`，说明可以尝试套用 [discuz.dc.js](https://github.com/miiwu/sspanel.soulsign/blob/master/application/discuz.dc.js)；
接下来可以去 [discuz.dc](https://soulsign.inu1255.cn/scripts/230) 看一下。

可以先尝试一下，再有问题的话，可以再沟通。

**Comment by poissr** [comment]
>https://sskft3.top/plugin.php?id=gsignin:index

例如这个网站的网址格式和作者您在魂签里发布的三种签到特征都不相符，但可以确认是由discuz搭建，能否直接套用？

**Comment by miiwu** [comment]
> 这个网站的网址格式和作者您在魂签里发布的三种签到特征都不相符，但可以确认是由discuz搭建，能否直接套用？

这种一般是不可以套用的；
因为不同插件他们的页面、关键字、请求的网址大多是不相同的。
